# install system packages and additional ones
- name: "Install dependencies, this may take a moment depending on disk and network connection"
  apt:
    pkg:
      - apt-transport-https
      - python-apt
      - python-minimal
      - ca-certificates
      - iftop
      - iotop
      - sshfs
      - rsync
      - curl
      - htop
      - gnupg
      - software-properties-common
      - vim
      - git
      - sudo
      - lvm2
    state: present